WallDistanceToShowBlocks: 5
WallHeight: 3
WallWidth: 5
WallMaterial: STAINED_GLASS 
WallDataValue: 14
Messages:
  Warnings:
    PositionSet: "&aPosition set successfully. Dont forget to use &f/CombatRestrain reload"
    Reloaded: "&aConfig was reloaded successfully"
  Errors:
    NotAllowed: "&cNot allowed"
    WrongIndex: "&cIndex must be 1 or 2"
    MustBePlayer: "&cOnly players can execute this command"
  Usage:
    SetPosition: "&eUsage: /CombatRestrain set <name> <index:1/2>"
    Reload: "&eUsage: /CombatRestrain reload"
Walls:
